# Module: zeek
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.7/filebeat-module-zeek.html

- module: zeek
  capture_loss:
    enabled: true
  connection:
    enabled: true
    var.paths: ["/opt/zeek/logs/current/conn.log"]
  dce_rpc:
    enabled: true
  dhcp:
    enabled: true
  dnp3:
    enabled: true
  dns:
    enabled: true
    var.paths: ["/opt/zeek/logs/current/dns.log"]
  dpd:
    enabled: true
  files:
    enabled: true
    var.paths: ["/opt/zeek/logs/current/files.log"]
  ftp:
    enabled: true
  http:
    enabled: true
  intel:
    enabled: true    
  irc:
    enabled: true
  kerberos:
    enabled: true
  modbus:
    enabled: true
  mysql:
    enabled: true
  notice:
    enabled: true
  ntlm:
    enabled: true
  ocsp:
    enabled: true
  pe:
    enabled: true
  radius:
    enabled: true
  rdp:
    enabled: true
  rfb:
    enabled: true
  signatures:
    enabled: false
  sip:
    enabled: true
  smb_cmd:
    enabled: true
  smb_files:
    enabled: true
  smb_mapping:
    enabled: true
  smtp:
    enabled: true
  snmp:
    enabled: true
  socks:
    enabled: true
  ssh:
    enabled: true
  ssl:
    enabled: true
    var.paths: ["/opt/zeek/logs/current/ssl.log"]
  stats:
    enabled: true
    var.paths: ["/opt/zeek/logs/current/stats.log"]
  syslog:
    enabled: true
  traceroute:
    enabled: true
  tunnel:
    enabled: true
  weird:
    enabled: true
    var.paths: ["/opt/zeek/logs/current/weird.log"]
  x509:
    enabled: true
    var.paths: ["/opt/zeek/logs/current/x509.log"]

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:
